language: node_js
node_js: 
  - "7"
install:
  - yarn
cache: yarn
service:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - DB_TEST=travis_ci_test
addons:
  postgresql: "9.4"